export class RouteConstants {
  static readonly CALENDAR_VIEW: string = 'CalendarView';
  static readonly LOGIN_PAGE: string = 'LoginPage';
  static readonly MANUAL_LOGIN_PAGE: string = 'ManualLoginPage';
  static readonly MEDITATIONS_PAGE: string = 'MeditationsPage';
  static readonly HEALTH_DATA_PAGE: string = 'HealthDataPage';
  static readonly SYMPTOMS_MOOD_PAGE: string = 'SymptomsMoodPage';
  static readonly SLEEP_CHART_PAGE: string = 'SleepChartPage';
  static readonly SUGGESTION_PAGE: string = 'SuggestionPage';
  static readonly HISTORY_PAGE: string = 'HistoryPage';
  static readonly BREATHE_PAGE: string = 'BreatheExercise';
}